apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  capacity:
    storage: 5Gi  # Adjust based on your PVC request
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""  # Use an empty string since the PVC does not have a storage class defined
  hostPath:
    path: "/mnt/data"  # Change to the appropriate directory if using AWS EBS, NFS, etc.

