apiVersion: v1                 # API version for Service objects
kind: Service                   # We are creating a Service
metadata:
  name: vote                   # Name of the Service
spec:
  type: NodePort               # Expose Service on each Node's IP at a static port
  selector:
    app: vote                  # Match Pods with label "app=vote"
  ports:
    - port: 80                 # Service port (inside cluster)
      targetPort: 80           # Forward traffic to container's port 80
      nodePort: 30001          # External access via NodeIP:30001
