apiVersion: apps/v1            # API version for Deployment resource
kind: Deployment               # We are creating a Deployment
metadata:
  name: vote                   # Name of the Deployment
  labels:
    app: vote                  # Label to identify this Deployment
spec:
  replicas: 2                  # Run 2 Pods for high availability
  selector:
    matchLabels:
      app: vote                # This Deployment manages Pods with label "app=vote"
  template:                     # Pod template (blueprint for Pods)
    metadata:
      labels:
        app: vote              # Each Pod created will have label "app=vote"
    spec:
      containers:              # Define container(s) inside the Pod
      - name: vote             # Name of the container
        image: donaemeka/voting-app-vote:latest   # Docker image for vote app
        ports:
        - containerPort: 80    # App inside the container listens on port 80
        env:                   # Environment variables for the container
        - name: REDIS_HOST     # Hostname of Redis service
          value: redis         # Points to Kubernetes Service 'redis'
        - name: REDIS_PORT     # Port number of Redis
          value: "6379"        # Default Redis port
