name: CI/CD Pipeline
run-name: ${{ github.actor }} is Deploying

on:
  push:
    branches:
      - main  # Trigger when pushing to the main branch
    tags:
      - '*'  # Trigger when a new tag is pushed
  workflow_dispatch:  # Allow manual triggering from GitHub UI

jobs:
  # Job for the vote service
  build-and-deploy-vote:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.ref_type == 'tag' && github.ref_name || github.sha }}  # Use tag or commit SHA as image tag
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4  # Checkout the repository code

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Docker Hub username stored in secrets
          password: ${{ secrets.DOCKER_PASSWORD }}  # Docker Hub password stored in secrets

      - name: Build and push vote service
        uses: docker/build-push-action@v6
        with:
          push: true  # Push the image to Docker Hub
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/vote:${{ env.IMAGE_TAG }}  # Build image with the commit SHA or tag
            ${{ secrets.DOCKER_USERNAME }}/vote:latest  # Push the latest tag

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}  # AWS access key stored in secrets
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # AWS secret access key stored in secrets
          aws-region: ${{ secrets.AWS_REGION }}  # AWS region stored in secrets

      - name: Install kubectl
        run: |
          curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.32.0/2024-12-20/bin/linux/amd64/kubectl  # Download kubectl
          chmod +x ./kubectl  # Make kubectl executable
          mkdir -p $HOME/bin  # Create bin directory
          mv ./kubectl $HOME/bin/kubectl  # Move kubectl to bin directory
          echo "::add-path::$HOME/bin"  # Add bin to PATH

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name ${{ secrets.AWS_CLUSTER }}  # Update kubeconfig to interact with EKS cluster

      - name: Generate the final deployment template for vote service
        run: |
          sudo apt-get update
          sudo apt-get install -y gettext-base  # Install gettext-base for environment variable substitution
          export IMAGE_NAME="docker.io/${{ secrets.DOCKER_USERNAME }}/vote:${{ env.IMAGE_TAG }}"  # Set image name
          envsubst < k8s/vote-deployment.template.yaml > k8s/vote-deployment.yaml  # Substitute environment variables into the template
          echo "Final vote-deployment.yaml:"  # Show final deployment file
          cat k8s/vote-deployment.yaml  # Display the deployment file

      - name: Deploy vote service to EKS
        run: |
          kubectl apply -f k8s/vote-deployment.yaml  # Deploy the vote service to EKS

  # The same correction applies to result and worker services:
  build-and-deploy-result:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.ref_type == 'tag' && github.ref_name || github.sha }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push result service
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/result:${{ env.IMAGE_TAG }}
            ${{ secrets.DOCKER_USERNAME }}/result:latest

      - name: Deploy result service to EKS
        run: |
          kubectl apply -f k8s/result-deployment.yaml

  build-and-deploy-worker:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.ref_type == 'tag' && github.ref_name || github.sha }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push worker service
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/worker:${{ env.IMAGE_TAG }}
            ${{ secrets.DOCKER_USERNAME }}/worker:latest

      - name: Deploy worker service to EKS
        run: |
          kubectl apply -f k8s/worker-deployment.yaml
