name: CI/CD Pipeline
run-name: ${{ github.actor }} is Deploying

on:
  push:
    branches:
      - main  # Trigger when pushing to the main branch
    tags:
      - '*'  # Trigger when a new tag is pushed
  workflow_dispatch:  # Allow manual triggering from GitHub UI

jobs:
  # Job for the vote service
  deploy-vote:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.sha }}  # Use commit SHA as image tag
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install kubectl
        run: |
          curl -LO https://dl.k8s.io/release/v1.32.0/bin/linux/amd64/kubectl
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name ${{ secrets.AWS_CLUSTER }}

      - name: Deploy vote service
        run: |
          export IMAGE_NAME="docker.io/donaemeka/vote:${{ env.IMAGE_TAG }}"
          envsubst < k8s/vote-deployment.template.yaml > k8s/vote-deployment.yaml
          kubectl apply -f k8s/vote-deployment.yaml

  # Job for the result service
  deploy-result:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.sha }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install kubectl
        run: |
          curl -LO https://dl.k8s.io/release/v1.32.0/bin/linux/amd64/kubectl
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name ${{ secrets.AWS_CLUSTER }}

      - name: Deploy result service
        run: |
          export IMAGE_NAME="docker.io/donaemeka/result:${{ env.IMAGE_TAG }}"
          envsubst < k8s/result-deployment.template.yaml > k8s/result-deployment.yaml
          kubectl apply -f k8s/result-deployment.yaml

  # Job for the worker service
  deploy-worker:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.sha }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install kubectl
        run: |
          curl -LO https://dl.k8s.io/release/v1.32.0/bin/linux/amd64/kubectl
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name ${{ secrets.AWS_CLUSTER }}

      - name: Deploy worker service
        run: |
          export IMAGE_NAME="docker.io/donaemeka/worker:${{ env.IMAGE_TAG }}"
          envsubst < k8s/worker-deployment.yaml > k8s/worker-deployment.yaml
          kubectl apply -f k8s/worker-deployment.yaml
